language: python

sudo: false

python:
    - 2.7
    - 3.5
    - 3.6

env:
  - TEST_TARGET=default
  - TEST_TARGET=coding

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --add channels conda-forge # for cell-tree_2D
    - travis_retry conda create --yes -n TEST python=$TRAVIS_PYTHON_VERSION nomkl --file requirements.txt
    - source activate TEST
    - travis_retry conda install --yes --file requirements-dev.txt
#    - travis_retry pip install -r requirements-dev.txt

install:
    - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install pyugrid-${version}.tar.gz && popd

script:
    - if [[ $TEST_TARGET == 'default' ]]; then
        python setup.py test -a '--verbose --cov=pyugrid';
      fi
    - if [[ $TEST_TARGET == 'coding' ]]; then
        find . -type f -name "*.py" ! -name 'conf.py' | xargs flake8 --max-line-length=100;
      fi

notifications:
    irc: "chat.freenode.net#renci"
